master:
  kode_toko: "Kode Toko"
  nama_toko: "Nama Toko"
  am: "AM"
  as: "AS"
  type_col: "TYPE"
  type_ayam: "FRIED CHICKEN"
  type_sosis: "SAUSAGE"
  jam: "JAM"
  target: "TARGET"
  realtime: "REALTIME"
  ach: "ACH"

parsing:
  pattern: 'TOKO:(?P<kode>[A-Z0-9]{4})-(?P<nama>[^|]+)\|\s*(?P<qty>\d+)\s*\|\s*(?P<rp>[\d,]+)\s*\|\s*(?P<stock>\d+)'

modul:
  ayam:
    folder: "data/incoming/ayam/"
    label: "Ayam (Fried Chicken)"
    type_master: "FRIED CHICKEN"
  sosis:
    folder: "data/incoming/sosis/"
    label: "Sosis (Hot Sausage)"
    type_master: "SAUSAGE"

ui:
  top_n: 10
  bottom_n: 10