master:
  kode_toko: "Kode Toko"
  nama_toko: "Nama Toko"
  am: "AM"
  as: "AS"
  type_col: "TYPE"
  type_ayam: "FRIED CHICKEN"
  type_sosis: "SOSIS"               # sesuai dengan isi kolom TYPE di Excel
  jam: "JAM"
  target: "TARGET"
  realtime: "REALTIME"
  ach: "ACH"

parsing:
  pattern: 'TOKO:(?P<kode>[A-Z0-9]{4})-(?P<nama>[^|]+)\|\s*(?P<qty>\d+)\s*\|\s*(?P<rp>[\d,]+)\s*\|\s*(?P<stock>\d+)'

modul:
  ayam:
    label: "Ayam (Fried Chicken)"
  sosis:
    label: "Sosis (Hot Sausage)"

ui:
  top_n: 5
  bottom_n: 5